{"uuid": "ea46ff8b-4059-4cde-aa98-8406a04a6944", "children": ["9ec884ff-090b-47a1-9b4a-eef8d32078bf"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at 'Saucedemo_Automation_AKGV/App/saucedemo.apk' does not exist or is not accessible\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: The application at 'Saucedemo_Automation_AKGV/App/saucedemo.apk' does not exist or is not accessible\n    at getResponseForW3CError (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9)\n    at asyncHandler (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37)\n", "trace": "  File \"/Users/agamav/Desktop/Training/Saucedemo_Automation_AKGV/venv/PythonProject/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/agamav/Desktop/Training/Saucedemo_Automation_AKGV/venv/PythonProject/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/agamav/Desktop/Training/Saucedemo_Automation_AKGV/venv/PythonProject/lib/python3.10/site-packages/_pytest/fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/agamav/Desktop/Training/Saucedemo_Automation_AKGV/tests/conftest.py\", line 19, in driver\n    driver = webdriver.Remote(URL, DESIRED_CAPABILITIES)\n  File \"/Users/agamav/Desktop/Training/Saucedemo_Automation_AKGV/venv/PythonProject/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 230, in __init__\n    super().__init__(\n  File \"/Users/agamav/Desktop/Training/Saucedemo_Automation_AKGV/venv/PythonProject/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 286, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/agamav/Desktop/Training/Saucedemo_Automation_AKGV/venv/PythonProject/lib/python3.10/site-packages/appium/webdriver/webdriver.py\", line 320, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"/Users/agamav/Desktop/Training/Saucedemo_Automation_AKGV/venv/PythonProject/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/agamav/Desktop/Training/Saucedemo_Automation_AKGV/venv/PythonProject/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1677185089731, "stop": 1677185089741}], "start": 1677185089731, "stop": 1677185089778}